### ISSUE TITLE
sengrid apiKey

### ISSUE THREAD

**Issue by janvv-visma** [daveRendon/azinsider#56]
Hi Dave,

Thanks a lot for your examples. I have one issue,though.

I used this example: application-workloads/logic-app-send-mail.

I noticed that the deployment succeeds, but that the app only works after manually adding the apikey in the API connection on the Azure Portal. For some reason it does not take the parameter value.
That's a bit of a pity if you want to have a fully automated deployment.

Have you any idea on how to solve that?

**Comment by daveRendon** [comment]
Hi @janvv-visma 

Appreciate your effort in running the sample. I've deployed it, and despite a warning in the portal, the logic app is functioning as intended.

Give it a test with this payload:
{
  "from": "my@email.com",
  "to": "your@email.com",
  "subject": "My logic app works",
  "emailbody": "Hello world"
}

Alternatively, consider storing the apiKey in KeyVault. Let me know if you spot any other issues. Thanks!
